version: "3.8"

services:
  mcp-server:
    build:
      context: .
      dockerfile: server.dockerfile 
    container_name: mcp-server
    ports:
      - "8000:8000"
    volumes:
      - ../src/:/app/src/
    env_file:
      - .env
